src/imagetagger/images/urls.py
from django.urls import path

from . import views

app_name = 'images'
urlpatterns = [
    path('', views.index, name='index'),
    path('image/delete/<int:image_id>/', views.delete_images, name='delete_images'),
    path('image/setfree/<int:imageset_id>/', views.set_free, name='setfree_imageset'),
    path('image/upload/<int:imageset_id>/', views.upload_image, name='upload_image'),
    path('image/<int:image_id>/', views.view_image, name='view_image'),
    path('imagelist/<int:image_set_id>/', views.list_images, name='list_images'),
    path('imageset/<int:imageset_id>/label-upload/', views.label_upload, name='label_upload'),
    path('imageset/create/', views.create_imageset, name='create_imageset'),
    path('imageset/<int:imageset_id>/delete/', views.delete_imageset, name='delete_imageset'),
    path('imageset/<int:imageset_id>/pin/', views.toggle_pin_imageset, name='pin_imageset'),
    path('imageset/<int:imageset_id>/edit/', views.edit_imageset, name='edit_imageset'),
    path('imageset/<int:image_set_id>/', views.view_imageset, name='view_imageset'),
    path('imageset/<int:image_set_id>/download/', views.download_imageset_zip, name='download_imageset'),
    path('imageset/explore/', views.explore_imageset, name='explore_imageset'),
    path('imageset/imagetagger_dl_script.py', views.dl_script, name='dl_script'),
    path('api/imageset/load/', views.load_image_set, name='load_image_set'),
    path('api/imageset/tag/add/', views.tag_image_set, name='tag_image_set'),
    path('api/imageset/tag/delete/', views.remove_image_set_tag, name='remove_image_set_tag'),
    path('api/imageset/tag/autocomplete/', views.autocomplete_image_set_tag, name='autocomplete_image_set_tag'),
]

src/imagetagger/urls.py
from django.urls import path, include
from django.contrib import admin
from django.shortcuts import render
from django_registration.backends.activation.views import RegistrationView

from .users.forms import UserRegistrationForm

urlpatterns = [
    path('user/', include('django.contrib.auth.urls')),
    path('accounts/register/', RegistrationView.as_view(form_class=UserRegistrationForm), name='django_registration_register'),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('', include('imagetagger.base.urls')),
    path('admin/', admin.site.urls),
    path('administration/', include('imagetagger.administration.urls')),
    path('annotations/', include('imagetagger.annotations.urls')),
    path('images/', include('imagetagger.images.urls')),
    path('users/', include('imagetagger.users.urls')),
    path('tagger_messages/', include('imagetagger.tagger_messages.urls')),
    path('tools/', include('imagetagger.tools.urls')),
]


def handler500(request):
    """500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """
    use_sentry = False
    sentry_dsn = None
    event_id = None
    try:
        import sentry_sdk
        if sentry_sdk.Hub.current.client:
            use_sentry = True
            sentry_dsn = sentry_sdk.Hub.current.client.dsn
            event_id = sentry_sdk.last_event_id()
    except ImportError:
        pass

    return render(request, '500.html', status=500, context={
        'use_sentry': use_sentry,
        'sentry_dsn': sentry_dsn,
        'event_id': event_id,
    })

src/imagetagger/images/models.py
from typing import Set

from fs import path
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

from imagetagger.users.models import Team


class Image(models.Model):
    image_set = models.ForeignKey(
        'ImageSet', on_delete=models.CASCADE, related_name='images')
    name = models.CharField(max_length=100)
    filename = models.CharField(max_length=100, unique=True)
    time = models.DateTimeField(auto_now_add=True)
    checksum = models.BinaryField()
    width = models.IntegerField(default=800)
    height = models.IntegerField(default=600)

    def path(self):
        return path.combine(self.image_set.root_path(), self.filename)

    def relative_path(self):
        return path.combine(self.image_set.path, self.filename)

    def delete(self, *args, **kwargs):
        self.image_set.zip_state = ImageSet.ZipState.INVALID
        self.image_set.save(update_fields=('zip_state',))
        super(Image, self).delete(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.image_set.zip_state = ImageSet.ZipState.INVALID
        self.image_set.save(update_fields=('zip_state',))
        super(Image, self).save(*args, **kwargs)

    def __str__(self):
        return u'Image: {0}'.format(self.name)


class ImageSet(models.Model):
    class Meta:
        unique_together = [
            'name',
            'team',
        ]

    class ZipState:
        INVALID = 0
        READY = 1
        PROCESSING = 2

    PRIORITIES = (
        (1, 'High'),
        (0, 'Normal'),
        (-1, 'Low'),
    )
    ZIP_STATES = (
        (ZipState.INVALID, 'invalid'),
        (ZipState.READY, 'ready'),
        (ZipState.PROCESSING, 'processing'),
    )

    path = models.CharField(max_length=100, unique=True, null=True)
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(max_length=1000, null=True, blank=True)
    time = models.DateTimeField(auto_now_add=True)
    team = models.ForeignKey(
        Team,
        on_delete=models.SET_NULL,
        related_name='image_sets',
        null=True,
    )
    creator = models.ForeignKey(settings.AUTH_USER_MODEL,
                                default=None,
                                on_delete=models.SET_NULL,
                                null=True,
                                blank=True)
    public = models.BooleanField(default=False)
    public_collaboration = models.BooleanField(default=False)
    image_lock = models.BooleanField(default=False)
    priority = models.IntegerField(choices=PRIORITIES, default=0)
    main_annotation_type = models.ForeignKey(
        to='annotations.AnnotationType',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        default=None
    )
    pinned_by = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='pinned_sets')
    zip_state = models.IntegerField(choices=ZIP_STATES, default=ZipState.INVALID)

    def root_path(self):
        return path.combine(settings.IMAGE_PATH, self.path)

    def tmp_path(self):
        return path.combine(settings.TMP_IMAGE_PATH, self.path)

    def relative_zip_path(self):
        return path.combine(self.path, self.zip_name())

    def zip_path(self):
        return path.combine(self.root_path(), self.zip_name())

    def tmp_zip_path(self):
        return path.combine(self.tmp_path(), self.zip_name())

    def zip_name(self):
        return "imageset_{}.zip".format(self.id)

    @property
    def image_count(self):
        if hasattr(self, 'image_count_agg'):
            return self.image_count_agg
        return self.images.count()

    def get_perms(self, user: get_user_model()) -> Set[str]:
        """Get all permissions of the user."""
        perms = set()
        if self.team is not None:
            if self.team.is_admin(user):
                perms.update({
                    'verify',
                    'annotate',
                    'create_export',
                    'delete_annotation',
                    'delete_export',
                    'delete_set',
                    'delete_images',
                    'edit_annotation',
                    'edit_set',
                    'read',
                })
            if self.team.is_member(user):
                perms.update({
                    'verify',
                    'annotate',
                    'create_export',
                    'delete_annotation',
                    'delete_export',
                    'edit_annotation',
                    'edit_set',
                    'read',
                })
            if user == self.creator:
                perms.update({
                    'verify',
                    'annotate',
                    'create_export',
                    'delete_annotation',
                    'delete_export',
                    'delete_set',
                    'delete_images',
                    'edit_annotation',
                    'edit_set',
                    'read',
                })
        if self.public:
            perms.update({
                'read',
                'create_export',
            })
            if self.public_collaboration:
                perms.update({
                    'verify',
                    'annotate',
                    'delete_annotation',
                    'edit_annotation',
                })
        return perms

    def has_perm(self, permission: str, user: get_user_model()) -> bool:
        """Check whether user has specified permission."""
        return permission in self.get_perms(user)

    def __str__(self):
        return u'Imageset: {0}'.format(self.name)

    @property
    def prio_symbol(self):
        if self.priority == -1:
            return '<span class="glyphicon glyphicon-download" data-toggle="tooltip" data-placement="right" title="Low labeling priority"></span>'
        elif self.priority == 0:
            return ''
        elif self.priority == 1:
            return '<span class="glyphicon glyphicon-exclamation-sign" data-toggle="tooltip" data-placement="right" title="High labeling priority"></span>'


class SetTag(models.Model):
    name = models.CharField(max_length=100, unique=True)
    imagesets = models.ManyToManyField(ImageSet, related_name='set_tags')

src/imagetagger/images/forms.py
from django import forms

from imagetagger.images.models import ImageSet


class ImageSetCreationForm(forms.ModelForm):
    class Meta:
        model = ImageSet
        fields = [
            'name',
            'location',
            'public',
            'public_collaboration',
        ]


class ImageSetCreationFormWT(forms.ModelForm):
    class Meta:
        model = ImageSet
        fields = [
            'name',
            'location',
            'public',
            'public_collaboration',
            'team',
        ]


class ImageSetEditForm(forms.ModelForm):
    class Meta:
        model = ImageSet
        fields = [
            'name',
            'location',
            'description',
            'public',
            'public_collaboration',
            'image_lock',
            'priority',
            'main_annotation_type',
        ]


class LabelUploadForm(forms.Form):
    file = forms.FileField()
    verify = forms.BooleanField(required=None)

src/imagetagger/images/templates/images/create_imageset.html
{% extends 'base/base.html' %}

{% load i18n %}
{% load widget_tweaks %}

{% block bodyblock %}
    <form method="POST" action="{% url 'images:create_imageset' team.id %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_name">{{ form.name.label }}</label>
            {% render_field form.name class+='form-control' %}
            {% for error in form.name.errors %}
                <div class="alert alert-warning">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            <label for="id_location">{{ form.location.label }}</label>
            {% render_field form.location class+='form-control' %}
            {% for error in form.location.errors %}
                <div class="alert alert-warning">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            <label for="id_public">{{ form.public.label }}</label>
            {% render_field form.public %}
            {% for error in form.public.errors %}
                <div class="alert alert-warning">{{ error }}</div>
            {% endfor %}
        </div>
        {% for error in form.non_field_errors %}
            <div class="alert alert-warning">{{ error }}</div>
        {% endfor %}
        <input type="submit" value="{% trans 'Create imageset' %}" class="btn btn-primary" />
    </form>
{% endblock bodyblock %}

src/imagetagger/images/templates/images/delete_imageset.html
{% extends 'base/base.html' %}
{% load i18n %}

{% block bodyblock %}
    <form method="POST" action="{% url 'images:delete_imageset' imageset.id %}">
        {% csrf_token %}
        {% blocktrans with imageset=imageset.name team=imageset.team.name %}
        <p>
            Are you sure that you want to delete the imageset
            <em>{{ imageset }}</em>
            of the team
            <em>{{ team }}</em>?
        </p>
        {% endblocktrans %}
        <a href="{% url 'images:view_imageset' imageset.pk %}" class="btn btn-default">{% trans 'Cancel' %}</a>
        <input type="submit" class="btn btn-danger" value="{% trans 'Delete imageset' %}" />
    </form>
{% endblock bodyblock %}

src/imagetagger/images/templates/images/edit_imageset.html
{% extends 'base/base.html' %}

{% load i18n %}
{% load widget_tweaks %}

{% block bodyblock %}
    <form method="POST" action="{% url 'images:edit_imageset' form.instance.pk %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_name">{{ form.name.label }}</label>
            {% render_field form.name class+='form-control' %}
            {% for error in form.name.errors %}
                <div class="alert alert-warning">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            <label for="id_location">{{ form.location.label }}</label>
            {% render_field form.location class+='form-control' %}
            {% for error in form.location.errors %}
                <div class="alert alert-warning">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            <label for="id_description">{{ form.description.label }}</label>
            {% render_field form.description class+='form-control' %}
            {% for error in form.description.errors %}
                <div class="alert alert-warning">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            <label for="id_public">{{ form.public.label }}</label>
            {% render_field form.public %}
            {% for error in form.public.errors %}
                <div class="alert alert-warning">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            <label for="id_image_lock">{{ form.image_lock.label }}</label>
            {% render_field form.image_lock %}
            {% for error in form.image_lock.errors %}
                <div class="alert alert-warning">{{ error }}</div>
            {% endfor %}
        </div>
        {% for error in form.non_field_errors %}
            <div class="alert alert-warning">{{ error }}</div>
        {% endfor %}
        <input type="submit" value="{% trans 'Update imageset' %}" class="btn btn-primary" />
    </form>
{% endblock bodyblock %}

src/imagetagger/images/templates/images/setfree_imageset.html
{% extends 'base/base.html' %}
{% load i18n %}

{% block bodyblock %}
    <form method="POST" action="{% url 'images:setfree_imageset' imageset.id %}">
        {% csrf_token %}
        {% blocktrans with imageset=imageset.name team=imageset.team.name %}
        <p>
            Are you sure that you want to give up ownership of the imageset
            <em>{{ imageset }}</em>
            of the team
            <em>{{ team }}</em>?
            This makes the imageset publicly available and means you lose all rights to manage this imageset.
        </p>
        {% endblocktrans %}
        <a href="{% url 'images:view_imageset' imageset.pk %}" class="btn btn-default">{% trans 'Cancel' %}</a>
        <input type="submit" class="btn btn-danger" value="{% trans 'Set imageset free' %}" />
    </form>
{% endblock bodyblock %}