imagetagger/imagetagger/administration/urls.py
from django.conf.urls import url

from . import views

app_name = 'administration'
urlpatterns = [
    url(r'^$', views.annotation_types, name='index'),
    url(r'^annotation_type/list/$', views.annotation_types, name='annotation_types'),
    url(r'^annotation_type/(\d+)/$', views.annotation_type, name='annotation_type'),
    url(r'^annotation_type/create/$', views.create_annotation_type, name='create_annotation_type'),
    url(r'^annotation_type/create_view/$', views.create_annotation_type_view, name='create_annotation_type_view'),
    url(r'^annotation_type/edit/(\d+)/$', views.edit_annotation_type, name='edit_annotation_type'),
    url(r'^annotation_type/migrate/bbt0p/(\d+)/$', views.migrate_bounding_box_to_0_polygon, name='migrate_bbt0p'),
    url(r'^annotation_type/migrate/bbt4p/(\d+)/$', views.migrate_bounding_box_to_4_polygon, name='migrate_bbt4p'),
]

imagetagger/imagetagger/administration/forms.py
from django import forms

from imagetagger.annotations.models import AnnotationType


class AnnotationTypeCreationForm(forms.ModelForm):
    class Meta:
        model = AnnotationType
        fields = [
            'name',
            'active',
            'node_count',
            'vector_type',
            'enable_concealed',
            'enable_blurred',
            'md_description',
        ]


class AnnotationTypeEditForm(forms.ModelForm):
    class Meta:
        model = AnnotationType
        fields = [
            'name',
            'active',
            'enable_concealed',
            'enable_blurred',
            'md_description',
        ]

imagetagger/imagetagger/administration/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.db import transaction

from .forms import AnnotationTypeCreationForm, AnnotationTypeEditForm
from imagetagger.annotations.models import Annotation, AnnotationType


@staff_member_required
def annotation_types(request):
    return render(request, 'administration/annotation_type.html', {
        'annotation_types': AnnotationType.objects.all().order_by('name'),
        'create_form': AnnotationTypeCreationForm(),
    })


@staff_member_required
def annotation_type(request, annotation_type_id):
    selected_annotation_type = get_object_or_404(AnnotationType, id=annotation_type_id)
    return render(request, 'administration/annotation_type.html', {
        'annotation_types': AnnotationType.objects.all().order_by('name'),
        'annotation_type': selected_annotation_type,
        'vector_type_name': AnnotationType.get_vector_type_name(selected_annotation_type.vector_type),
        'create_form': AnnotationTypeCreationForm(),
        'edit_form': AnnotationTypeEditForm(instance=selected_annotation_type)
    })


@staff_member_required
def create_annotation_type(request):
    if request.method == 'POST':
        form = AnnotationTypeCreationForm(request.POST)
        if form.is_valid():
            if AnnotationType.objects.filter(name=form.cleaned_data.get('name')).exists():
                form.add_error(
                    'name',
                    _('The name is already in use by an annotation type.'))
            else:
                with transaction.atomic():

                    type = form.save()

                messages.success(request, _('The annotation type was created successfully.'))
                return redirect(reverse('administration:annotation_type', args=(type.id,)))
    else:
        return redirect(reverse('administration:annotation_types'))


@staff_member_required
def create_annotation_type_view(request):
    return render(request, 'administration/annotation_type_create.html', {
        'annotation_types': AnnotationType.objects.all().order_by('name'),
        'create_form': AnnotationTypeCreationForm(),
        'creation': True
    })


@staff_member_required
def edit_annotation_type(request, annotation_type_id):
    selected_annotation_type = get_object_or_404(AnnotationType, id=annotation_type_id)
    if request.method == 'POST':
        if not request.POST['name'] == selected_annotation_type.name and AnnotationType.objects.filter(
                name=request.POST['name']).exists():
            messages.error(request, _('The name is already in use by an annotation type.'))
        else:
            selected_annotation_type.name = request.POST['name']
            selected_annotation_type.active = 'active' in request.POST.keys()
            selected_annotation_type.enable_concealed = 'enable_concealed' in request.POST.keys()
            selected_annotation_type.enable_blurred = 'enable_blurred' in request.POST.keys()
            selected_annotation_type.md_description = request.POST['md_description']
            selected_annotation_type.save()

            messages.success(request, _('The annotation type was edited successfully.'))
    return redirect(reverse('administration:annotation_type', args=(annotation_type_id,)))


@staff_member_required
def migrate_bounding_box_to_0_polygon(request, annotation_type_id):
    selected_annotation_type = get_object_or_404(AnnotationType, id=annotation_type_id)

    if selected_annotation_type.vector_type is AnnotationType.VECTOR_TYPE.BOUNDING_BOX:
        annotations = Annotation.objects.filter(annotation_type=selected_annotation_type)
        for annotation in annotations:
            annotation.verifications.all().delete()
            if annotation.vector:
                annotation.vector = {
                    'x1': annotation.vector['x1'],
                    'y1': annotation.vector['y1'],
                    'x2': annotation.vector['x2'],
                    'y2': annotation.vector['y1'],
                    'x3': annotation.vector['x2'],
                    'y3': annotation.vector['y2'],
                    'x4': annotation.vector['x1'],
                    'y4': annotation.vector['y2'],
                }
            annotation.save()
        selected_annotation_type.vector_type = AnnotationType.VECTOR_TYPE.POLYGON
        selected_annotation_type.node_count = 0
        selected_annotation_type.save()
    return redirect(reverse('administration:annotation_type', args=(annotation_type_id,)))


@staff_member_required
def migrate_bounding_box_to_4_polygon(request, annotation_type_id):
    selected_annotation_type = get_object_or_404(AnnotationType, id=annotation_type_id)

    if selected_annotation_type.vector_type is AnnotationType.VECTOR_TYPE.BOUNDING_BOX:
        annotations = Annotation.objects.filter(annotation_type=selected_annotation_type)
        for annotation in annotations:
            annotation.verifications.all().delete()
            if annotation.vector:
                annotation.vector = {
                    'x1': annotation.vector['x1'],
                    'y1': annotation.vector['y1'],
                    'x2': annotation.vector['x2'],
                    'y2': annotation.vector['y1'],
                    'x3': annotation.vector['x2'],
                    'y3': annotation.vector['y2'],
                    'x4': annotation.vector['x1'],
                    'y4': annotation.vector['y2'],
                }
            annotation.save()
        selected_annotation_type.vector_type = AnnotationType.VECTOR_TYPE.POLYGON
        selected_annotation_type.node_count = 4
        selected_annotation_type.save()
    return redirect(reverse('administration:annotation_type', args=(annotation_type_id,)))

imagetagger/imagetagger/administration/templates/administration/annotation_type.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load static %}


{% block bodyblock %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            {% if annotation_type %}
                <h2>Annotation Type "{{ annotation_type.name }}"</h2>
            {% else %}
                <h2>Annotation Types</h2>
            {% endif %}
        </div>
    </div>
</div>
<div class="row" style="margin-top: 1em">
    <div class="col-md-3">
        {% include "administration/annotation_types_list.html" %}
    </div>
    {% if annotation_type %}
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Edit "{{ annotation_type.name }}"</h3>
            </div>
            <div class="panel-body">
                <form action="{% url "administration:edit_annotation_type" annotation_type.id %}"
                      method="POST">
                    <table class="table table-striped">
                        <tbody>
                            {% csrf_token %}
                            <tr>
                                <td>
                                    <label for="id_name">{{ edit_form.name.label }}</label>
                                </td>
                                <td>
                                    {% render_field edit_form.name class+='form-control' %}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <label for="id_active">{{ edit_form.active.label }}</label>
                                </td>
                                <td>
                                    {% render_field edit_form.active class+='form-control' %}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <label for="id_enable_blurred">{{ edit_form.enable_blurred.label }}</label>
                                </td>
                                <td>
                                    {% render_field edit_form.enable_blurred class+='form-control' %}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <label for="id_enable_concealed">{{ edit_form.enable_concealed.label }}</label>
                                </td>
                                <td>
                                    {% render_field edit_form.enable_concealed class+='form-control' %}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <b>Vector Type</b>
                                </td>
                                <td>
                                    {{ vector_type_name }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <b>Node count</b>
                                </td>
                                <td>
                                    {{ annotation_type.node_count }}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <hr>
                    <label for="id_md_description">Description</label>
                    <span data-toggle="tooltip" data-placement="right"
                          title="Support for markdown-language."
                          class="glyphicon glyphicon-question-sign">
                    </span>
                    <p class="pull-right">
                        {% include 'base/markdown_guide.html' %}
                    </p>
                    {% render_field edit_form.md_description class+='form-control' %}
                    <hr>
                    <div align="right">
                        <input class="btn btn-primary right" type="submit" value="Save">
                    </div>
                </form>
                {% if annotation_type.vector_type == 1 %}
                <div class="panel-body">
                    Changing the vector type requires a migration of the annotations. <br>
                    <div class="alert alert-danger">
                        It is a non reversible process. No warranties!
                    </div>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-danger btn-lg" data-toggle="modal"
                            data-target="#migrationModal">
                        Migrate
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="migrationModal" tabindex="-1" role="dialog"
                         aria-labelledby="migrationModalLabel">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal"
                                            aria-label="Close">
                                        <span aria-hidden="true">
                                            &times;
                                        </span>
                                    </button>
                                    <h4 class="modal-title" id="migrationModalLabel">
                                        Migrate Annotation Type
                                    </h4>
                                </div>
                                <div class="modal-body">
                                    You can migrate the Annotation Type to a polygon with ether unlimited or 4 nodes.<br>
                                    Again: <br>
                                    <div class="alert alert-danger">
                                        It is a non reversible process. No warranties!
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">
                                        Close
                                    </button>
                                    <a class="btn btn-danger"
                                       href="{% url 'administration:migrate_bbt0p' annotation_type.id %}">
                                        Unlimited Nodes
                                    </a>
                                    <a class="btn btn-danger"
                                       href="{% url 'administration:migrate_bbt4p' annotation_type.id %}">
                                        4 Nodes
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">
                                Close
                            </button>
                            <a class="btn btn-danger"
                               href="{% url 'administration:migrate_bbt0p' annotation_type.id %}">
                                Unlimited Nodes
                            </a>
                            <a class="btn btn-danger"
                               href="{% url 'administration:migrate_bbt4p' annotation_type.id %}">
                                4 Nodes
                            </a>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    {% endif %}
</div>
{{ create_form.media }}
{% endblock %}

imagetagger/imagetagger/administration/templates/administration/annotation_type_create.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block bodyblock %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h2>Create new annotation type</h2>
            </div>
        </div>
        <div class="row" style="margin-top: 1em">
            <div class="col-md-3">
                {% include "administration/annotation_types_list.html" %}
            </div>
            <div class="col-md-9">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Create new annotation type</h3>
                    </div>
                    <div class="panel-body">
                        <form action="{% url "administration:create_annotation_type" %}" method="POST">
                            <table class="table table-striped">
                                <tbody>
                                {% csrf_token %}
                                <tr>
                                    <td>
                                        <label for="id_name">{{ create_form.name.label }}</label>
                                    </td>
                                    <td>
                                        {% render_field create_form.name class+='form-control' %}
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <label for="id_active">{{ create_form.active.label }}</label>
                                    </td>
                                    <td>
                                        {% render_field create_form.active class+='form-control' %}
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <label for="id_enable_blurred">{{ create_form.enable_blurred.label }}</label>
                                    </td>
                                    <td>
                                        {% render_field create_form.enable_blurred class+='form-control' %}
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <label for="id__enable_concealed">{{ create_form.enable_concealed.label }}</label>
                                    </td>
                                    <td>
                                        {% render_field create_form.enable_concealed class+='form-control' %}
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <label for="id_vector_type">{{ create_form.vector_type.label }}</label>
                                    </td>
                                    <td>
                                        <select name="{{ create_form.vector_type.name }}">
                                            <option value="1" selected>Bounding Box</option>
                                            <option value="2">Point</option>
                                            <option value="3">Line</option>
                                            <option value="4">Multiline</option>
                                            <option value="5">Polygon</option>
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <label for="id_node_count">{{ create_form.node_count.label }} <span
                                                data-toggle="tooltip" data-placement="right"
                                                title="The number of nodes in a polygon. 0 allows an arbitrary node count. This has no effect on other vector types."
                                                class="glyphicon glyphicon-question-sign"></span></label>
                                    </td>
                                    <td>
                                        {% render_field create_form.node_count class+='form-control' %}
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                            <hr>
                            <label for="id_md_description">Description</label>
                            <span data-toggle="tooltip" data-placement="right" title="Support for markdown-language."
                                  class="glyphicon glyphicon-question-sign"></span>
                            <p class="pull-right">
                                {% include 'base/markdown_guide.html' %}
                            </p>
                            {% render_field create_form.md_description class+='form-control' %}
                            <hr>
                            <input class="btn btn-danger pull-left" type="reset" value="Reset">
                            <input class="btn btn-primary pull-right" type="submit" value="Create">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{ create_form.media }}
{% endblock %}

imagetagger/imagetagger/administration/templates/administration/annotation_types_list.html
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title pull-left">
            <h3 style="margin-top: 0.2em">Edit annotation Types</h3>
        </div>
        {% if not creation %}
            <div class="panel-title pull-right">
                <a href="{% url 'administration:create_annotation_type_view' %}"
                   class="glyphicon glyphicon-plus btn btn-default">
                    <span style="font-family: sans-serif">New…</span>
                </a>
            </div>
        {% endif %}
        <div class="clearfix"></div>
    </div>
    <div class="panel-body">
        <ul>
            {% for list_annotation_type in annotation_types %}
                <li>
                    {% if list_annotation_type == annotation_type %}
                        <b>
                            {{ list_annotation_type.name }}
                        </b>
                    {% else %}
                        <a href="{% url "administration:annotation_type" list_annotation_type.id %}">
                            {{ list_annotation_type.name }}
                        </a>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
</div>