src/imagetagger/administration/urls.py
from django.urls import path

from . import views

app_name = 'administration'
urlpatterns = [
    path('', views.annotation_types, name='index'),
    path('annotation_type/list/', views.annotation_types, name='annotation_types'),
    path('annotation_type/<int:annotation_type_id>/', views.annotation_type, name='annotation_type'),
    path('annotation_type/create/', views.create_annotation_type, name='create_annotation_type'),
    path('annotation_type/edit/<int:annotation_type_id>/', views.edit_annotation_type, name='edit_annotation_type'),
    path('annotation_type/migrate/bbt0p/<int:annotation_type_id>/', views.migrate_bounding_box_to_0_polygon, name='migrate_bbt0p'),
    path('annotation_type/migrate/bbt4p/<int:annotation_type_id>/', views.migrate_bounding_box_to_4_polygon, name='migrate_bbt4p'),
]

src/imagetagger/base/urls.py
from django.urls import path

from . import views

app_name = 'base'
urlpatterns = [
    path('', views.index, name='index'),
    path('problems/', views.problem_report, name='problem')
]

src/imagetagger/images/urls.py
from django.urls import path

from . import views

app_name = 'images'
urlpatterns = [
    path('', views.index, name='index'),
    path('image/delete/<int:image_id>/', views.delete_images, name='delete_images'),
    path('image/setfree/<int:imageset_id>/', views.set_free, name='setfree_imageset'),
    path('image/upload/<int:imageset_id>/', views.upload_image, name='upload_image'),
    path('image/<int:image_id>/', views.view_image, name='view_image'),
    path('imagelist/<int:image_set_id>/', views.list_images, name='list_images'),
    path('imageset/<int:imageset_id>/label-upload/', views.label_upload, name='label_upload'),
    path('imageset/create/', views.create_imageset, name='create_imageset'),
    path('imageset/<int:imageset_id>/delete/', views.delete_imageset, name='delete_imageset'),
    path('imageset/<int:imageset_id>/pin/', views.toggle_pin_imageset, name='pin_imageset'),
    path('imageset/<int:imageset_id>/edit/', views.edit_imageset, name='edit_imageset'),
    path('imageset/<int:image_set_id>/', views.view_imageset, name='view_imageset'),
    path('imageset/<int:image_set_id>/download/', views.download_imageset_zip, name='download_imageset'),
    path('imageset/explore/', views.explore_imageset, name='explore_imageset'),
    path('imageset/imagetagger_dl_script.py', views.dl_script, name='dl_script'),
    path('api/imageset/load/', views.load_image_set, name='load_image_set'),
    path('api/imageset/tag/add/', views.tag_image_set, name='tag_image_set'),
    path('api/imageset/tag/delete/', views.remove_image_set_tag, name='remove_image_set_tag'),
    path('api/imageset/tag/autocomplete/', views.autocomplete_image_set_tag, name='autocomplete_image_set_tag'),
]

src/imagetagger/tools/urls.py
from django.urls import path

from . import views

app_name = 'tools'
urlpatterns = [
    path('', views.overview, name='overview'),
    path('create/', views.create_tool, name='create'),
    path('delete/<int:tool_id>/', views.delete_tool, name='delete'),
    path('edit/<int:tool_id>/', views.edit_tool, name='edit'),
    path('download/<int:tool_id>/', views.download_tool, name='download'),
]

src/imagetagger/urls.py
from django.urls import path, include
from django.contrib import admin
from django.shortcuts import render
from django_registration.backends.activation.views import RegistrationView

from .users.forms import UserRegistrationForm

urlpatterns = [
    path('user/', include('django.contrib.auth.urls')),
    path('accounts/register/', RegistrationView.as_view(form_class=UserRegistrationForm), name='django_registration_register'),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('', include('imagetagger.base.urls')),
    path('admin/', admin.site.urls),
    path('administration/', include('imagetagger.administration.urls')),
    path('annotations/', include('imagetagger.annotations.urls')),
    path('images/', include('imagetagger.images.urls')),
    path('users/', include('imagetagger.users.urls')),
    path('tagger_messages/', include('imagetagger.tagger_messages.urls')),
    path('tools/', include('imagetagger.tools.urls')),
]


def handler500(request):
    """500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """
    use_sentry = False
    sentry_dsn = None
    event_id = None
    try:
        import sentry_sdk
        if sentry_sdk.Hub.current.client:
            use_sentry = True
            sentry_dsn = sentry_sdk.Hub.current.client.dsn
            event_id = sentry_sdk.last_event_id()
    except ImportError:
        pass

    return render(request, '500.html', status=500, context={
        'use_sentry': use_sentry,
        'sentry_dsn': sentry_dsn,
        'event_id': event_id,
    })

src/imagetagger/users/urls.py
from django.urls import path

from . import views


app_name = 'users'
urlpatterns = [
    path('api/user/autocomplete/', views.user_autocomplete, name='user_autocomplete'),
    path('team/<int:team_id>/', views.view_team, name='team'),
    path('team/create/', views.create_team, name='create_team'),
    path('team/explore/', views.explore_team, name='explore_team'),
    path('team/<int:team_id>/add/', views.add_team_member, name='add_team_member'),
    path('team/<int:team_id>/leave/', views.leave_team, name='leave_team'),
    path('team/<int:team_id>/leave/<int:user_id>/', views.leave_team, name='leave_team'),
    path('team/<int:team_id>/grant_admin/<int:user_id>/', views.grant_team_admin, name='grant_team_admin'),
    path('team/<int:team_id>/revoke_admin/<int:user_id>/', views.revoke_team_admin, name='revoke_team_admin'),
    path('user/<int:user_id>/', views.user, name='user'),
    path('user/<int:user_id>/delete/', views.delete_account, name='delete_account'),
    path('user/explore/', views.explore_user, name='explore_user'),
]

src/imagetagger/base/models.py
# Create your models here.

src/imagetagger/base/views.py
from django.conf import settings
from django.shortcuts import redirect, render
from django.urls import reverse


def index(request):
    return redirect(reverse('images:index'))


def problem_report(request):
    if settings.PROBLEMS_TEXT != '':
        return render(request, 'base/problem.html', {
            'text': settings.PROBLEMS_TEXT
        })
    else:
        return redirect(settings.PROBLEMS_URL)

src/imagetagger/base/templates/base/base.html
{% load static %}<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <link rel="shortcut icon" type="image/png" href="{% static 'symbols/bitbots-fav.ico' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />
        {% block taggerimports %}{% endblock %}
        <title>Bit-Bots ImageTagger</title>
    </head>
    <body>
        {% block selectorblock %}{% endblock %}
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                  <a class="navbar-brand bitbot-logo" href="https://www.bit-bots.de" target="_blank"><img src="{% static 'symbols/bitbots-logo.png' %}" height="40px"></a>
                  <a class="navbar-brand"  href="{% url 'images:index' %}">ImageTagger</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'images:index' %}">Home</a></li>
                        {% block navblock %}{% endblock %}
                        {% if request.user.is_authenticated %}
                        <li><a href="{% url 'images:explore_imageset' %}">Explore</a></li>
                        <li>
                            <div style="height:50px">
                                <a class="upper-bandage-parent" href="{% url 'tagger_messages:overview' %}">
                                Messages 
                                {% if unread_message_count %}
                                <span class="badge upper-bandage">
                                    {% if unread_message_count < 10 %}
                                        {{unread_message_count}}
                                    {% else %}
                                        9+
                                    {% endif %}
                                </span>
                                {% endif %}
                            </a>
                            </div>
                        </li>
                        {% if TOOLS_ENABLED %}
                        <li><a href="{% url 'tools:overview' %}">Tools</a></li>
                        {% endif %}
                        {% if my_teams %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Teams <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                {% for team in my_teams %}
                                <li><a href="{% url 'users:team' team.id %}">{{team.name}}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                        {% endif %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user.username }} <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'users:user' user.id %}">Profile</a> </li>
                                <li><a href="{% url 'logout' %}">Logout</a></li>
                                <li><a href="{% url 'password_change' %}">Change Password</a></li>
                            </ul>
                        </li>
                        {% else %}
                            <li><a href="{% url 'login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div class="content container-fluid">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
            <noscript><div class="alert alert-danger">Appearently, you have JavaScript disabled. This website will not work properly without JavaScript</div></noscript>
            {% block bodyblock %}{% endblock %}
        </div>
        <footer class="footer">
            <div class="container">
                <p class="text-muted text-right">
                    {% if user.is_staff %}
                        <a href="{% url 'administration:index' %}">
                            Administration
                        </a>&nbsp;&nbsp;&nbsp;&nbsp;
                    {% endif %}
                    <a target="_blank" href="https://github.com/bit-bots/imagetagger">
                        This project on GitHub
                    </a>&nbsp;&nbsp;&nbsp;&nbsp;
                    <a target="_blank" href="{% url 'base:problem' %}">
                        Report an issue
                    </a>&nbsp;&nbsp;&nbsp;&nbsp;
                    {% if USE_IMPRINT %}
                        <a href="{{ IMPRINT_URL }}">{{ IMPRINT_NAME }}</a>
                    {% endif %}
                </p>
            </div>
        </footer>
        <script type="text/javascript" src="{% static 'scripts/jquery-3.2.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'scripts/bootstrap.min.js' %}"></script>
        {% block additional_js %}{% endblock additional_js %}
    </body>
</html>

src/imagetagger/base/templates/base/explore.html
{% extends 'base/base.html' %}
{% load static %}
{% block additional_js %}
<script type="text/javascript" src="{% static 'scripts/jquery.autocomplete.js' %}"></script>
<script type="text/javascript" src="{% static 'scripts/explore.js' %}"></script>
{% endblock %}
{% block bodyblock %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <h1>Explore {{mode}}s</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="list-group">
                <a class="list-group-item{% if mode == 'imageset' %} active{% endif %}" href="{% url 'images:explore_imageset' %}">Imagesets</a>
                <a class="list-group-item{% if mode == 'team' %} active{% endif %}" href="{% url 'users:explore_team' %}">Teams</a>
                <a class="list-group-item{% if mode == 'user' %} active{% endif %}" href="{% url 'users:explore_user' %}">Users</a>
            </div>
        </div>
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form action="{{ request.get_full_path }}" method="GET">
                                <div class="input-group {% if mode == 'imageset' %}set-search{% endif %}" role="group" aria-label="input-group">
                                    <input class="form-control" id="searchbox" type="text" name="query" placeholder="Search for {{mode}}s" {% if query %}value="{{ query }}"{% endif %}>
                                    {% if mode == 'imageset' %}<input class="form-control" id="tagbox" type="text" name="tags" placeholder="Search for comma-separated tags" {% if tagfilter %}value="{{ tagfilter }}"{% endif %} autocomplete="off">{% endif %}
                                    <span class="input-group-btn">
                                        <button class="btn btn-primary" type="submit">
                                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search
                                        </button>
                                    </span>
                                </div>
                            </form>
                            <hr>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <dl>
                                <table class="table table-striped">
                                {% for imageset in imagesets %}
                                    <tr>
                                        <td>
                                            <dt>
                                                {% if imageset.team %}
                                                    <a href="{% url 'users:team' imageset.team.id %}">{{imageset.team.name}}</a>/<a href="{% url 'images:view_imageset' imageset.id %}">{{imageset.name}}</a>
                                                {% else %}
                                                    <a href="{% url 'images:view_imageset' imageset.id %}">{{imageset.name}}</a>
                                                {% endif %}
                                            </dt>
                                            <dt>
                                                {% for tag in imageset.set_tags.all %}
                                                    <a href="{% url 'images:explore_imageset' %}?tags={{ tag.name }}, " class="label label-info">{{ tag.name }}</a>
                                                {% endfor %}
                                            </dt>
                                            <dd>
                                                {{ imageset.location }}
                                            </dd>
                                        </td>
                                    </tr>
                                {% endfor %}
                                {% for team in teams %}
                                    <tr>
                                        <td>
                                            <dt>
                                                <a href="{% url 'users:team' team.id %}">{{team.name}}</a>
                                            </dt>
                                        </td>
                                    </tr>
                                {% endfor %}
                                {% for user in users %}
                                    <tr>
                                        <td>
                                            <dt>
                                                <a href="{% url 'users:user' user.id %}">{{user.username}}</a>
                                            </dt>
                                        </td>
                                        <td class="align-right">
                                            {% if user.points %}
                                                {{ user.points }}
                                            {% else %}
                                                0
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </table>
                            </dl>
                            {% if paginator.has_other_pages %}
                                <div class="pagination">
                                    <hr>
                                    <span class="step-links">
                                        <div class="btn-group" role="group" aria-label="btn-group">
                                            {% if paginator.has_previous %}
                                                <a class="btn btn-default" href="?page=1{{ get_query }}{{ get_tagfilter }}">&laquo; first</a>
                                                <a class="btn btn-default" href="?page={{ paginator.previous_page_number }}{{ get_query }}{{ get_tagfilter }}">previous</a>
                                            {% endif %}
                                                <span class="current btn btn-default">
                                                    Page {{ paginator.number }} of {{ paginator.paginator.num_pages }}
                                                </span>
                                            {% if paginator.has_next %}
                                                <a class="btn btn-default" href="?page={{ paginator.next_page_number }}{{ get_query }}{{ get_tagfilter }}">next</a>
                                                <a class="btn btn-default" href="?page={{ paginator.paginator.num_pages }}{{ get_query }}{{ get_tagfilter }}">last &raquo;</a>
                                            {% endif %}
                                        </div>
                                    </span>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

src/imagetagger/base/templates/base/problem.html
{% extends "base/base.html" %}
{% load static %}

{% block bodyblock %}
    <div class="container"><section class="section">
        <div class="col-md-5">
            <h1>Report a problem</h1>
            <p>{{ text }}</p>
        </div>
    </section> </div>
{% endblock %}