src/imagetagger/tools/urls.py
from django.urls import path

from . import views

app_name = 'tools'
urlpatterns = [
    path('', views.overview, name='overview'),
    path('create/', views.create_tool, name='create'),
    path('delete/<int:tool_id>/', views.delete_tool, name='delete'),
    path('edit/<int:tool_id>/', views.edit_tool, name='edit'),
    path('download/<int:tool_id>/', views.download_tool, name='download'),
]

src/imagetagger/urls.py
from django.urls import path, include
from django.contrib import admin
from django.shortcuts import render
from django_registration.backends.activation.views import RegistrationView

from .users.forms import UserRegistrationForm

urlpatterns = [
    path('user/', include('django.contrib.auth.urls')),
    path('accounts/register/', RegistrationView.as_view(form_class=UserRegistrationForm), name='django_registration_register'),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('', include('imagetagger.base.urls')),
    path('admin/', admin.site.urls),
    path('administration/', include('imagetagger.administration.urls')),
    path('annotations/', include('imagetagger.annotations.urls')),
    path('images/', include('imagetagger.images.urls')),
    path('users/', include('imagetagger.users.urls')),
    path('tagger_messages/', include('imagetagger.tagger_messages.urls')),
    path('tools/', include('imagetagger.tools.urls')),
]


def handler500(request):
    """500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """
    use_sentry = False
    sentry_dsn = None
    event_id = None
    try:
        import sentry_sdk
        if sentry_sdk.Hub.current.client:
            use_sentry = True
            sentry_dsn = sentry_sdk.Hub.current.client.dsn
            event_id = sentry_sdk.last_event_id()
    except ImportError:
        pass

    return render(request, '500.html', status=500, context={
        'use_sentry': use_sentry,
        'sentry_dsn': sentry_dsn,
        'event_id': event_id,
    })

src/imagetagger/users/urls.py
from django.urls import path

from . import views


app_name = 'users'
urlpatterns = [
    path('api/user/autocomplete/', views.user_autocomplete, name='user_autocomplete'),
    path('team/<int:team_id>/', views.view_team, name='team'),
    path('team/create/', views.create_team, name='create_team'),
    path('team/explore/', views.explore_team, name='explore_team'),
    path('team/<int:team_id>/add/', views.add_team_member, name='add_team_member'),
    path('team/<int:team_id>/leave/', views.leave_team, name='leave_team'),
    path('team/<int:team_id>/leave/<int:user_id>/', views.leave_team, name='leave_team'),
    path('team/<int:team_id>/grant_admin/<int:user_id>/', views.grant_team_admin, name='grant_team_admin'),
    path('team/<int:team_id>/revoke_admin/<int:user_id>/', views.revoke_team_admin, name='revoke_team_admin'),
    path('user/<int:user_id>/', views.user, name='user'),
    path('user/<int:user_id>/delete/', views.delete_account, name='delete_account'),
    path('user/explore/', views.explore_user, name='explore_user'),
]

src/imagetagger/tools/models.py
from typing import Set

from imagetagger.users.models import Team
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model


class Tool(models.Model):
    name = models.CharField(max_length=100)
    filename = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)
    public = models.BooleanField(default=False)
    team = models.ForeignKey(Team,
                             on_delete=models.SET_NULL,
                             related_name='tool_team',
                             null=True,
                             blank=True)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.SET_NULL,
                                related_name='tool_creator',
                                null=True,
                                blank=True)

    @property
    def internal_filename(self):
        return '{0}_{1}'.format(self.id, self.name)

    def get_perms(self, user: get_user_model()) -> Set[str]:
        """Get all permissions of the user."""
        perms = set()
        if self.creator is not None and self.creator.id is user.id:
            perms.update({
                'edit_tool',
                'delete_tool',
                'download_tool',
                'see_tool',
            })
        if self.team is not None:
            if self.team.is_admin(user):
                perms.update({
                    'edit_tool',
                    'delete_tool',
                    'download_tool',
                    'see_tool',
                })
            if self.team.is_member(user):
                perms.update({
                    'download_tool',
                    'see_tool',
                })
        if self.public:
            perms.update({
                'download_tool',
                'see_tool',
            })
        return perms

    def has_perm(self, permission: str, user: get_user_model()) -> bool:
        """Check whether user has a specified permission."""
        return permission in self.get_perms(user)


class ToolVote(models.Model):
    class Meta:
        unique_together = [
            'tool',
            'user',
        ]

    tool = models.ForeignKey(
        Tool, on_delete=models.CASCADE, related_name='tool')
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL,
                             null=True,
                             blank=True)
    time = models.DateTimeField(auto_now_add=True)
    positive = models.BooleanField(default=0)

src/imagetagger/tools/forms.py
from django import forms

from imagetagger.tools.models import Tool
from django.core.exceptions import ValidationError


# found this under:
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
def file_size(value):
    limit = 2 * 1024 * 1024
    if value.size > limit:
        raise ValidationError('File too large. Size should not exceed 2 MiB.')


class ToolUploadForm(forms.ModelForm):
    class Meta:
        model = Tool
        fields = [
            'team',
            'name',
            'description',
            'public',
        ]
    file = forms.FileField(max_length=250, required=True, validators=[file_size])


class FileUploadForm(forms.Form):
    file = forms.FileField(max_length=250, required=False, validators=[file_size])

src/imagetagger/tools/views.py
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.urls import reverse
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.db import transaction
from django.db.models import Q
from django.template.response import TemplateResponse
from django.contrib import messages
from fs.errors import ResourceNotFound
from .models import Tool
from .forms import ToolUploadForm, FileUploadForm
from imagetagger.users.models import Team
from imagetagger.base.filesystem import root


def tools_enabled(in_function):
    if not settings.TOOLS_ENABLED:
        raise Http404
    return in_function


@tools_enabled
@login_required
def overview(request):
    tools = Tool.objects.select_related('team').order_by(
        'name').filter(
        Q(creator=request.user) | Q(team__members=request.user) | Q(public=True)).distinct()
    delete_tools = [tool.id for tool in tools if tool.has_perm('delete_tool', request.user)]
    edit_tools = [tool.id for tool in tools if tool.has_perm('edit_tool', request.user)]
    tool_form = ToolUploadForm()
    tool_form.fields['team'].queryset = Team.objects.filter(members=request.user)
    return TemplateResponse(request, 'overview.html', {
        'tools': tools,
        'edit_tools': edit_tools,
        'delete_tools': delete_tools,
        'form': tool_form,
        'file_form': FileUploadForm(),
        'tool_upload_notice': settings.TOOL_UPLOAD_NOTICE,
    })


@tools_enabled
@login_required
def create_tool(request):
    if request.method == 'POST':
        form = ToolUploadForm(request.POST, request.FILES)
        if form.is_valid():
            tool = form.instance
            # TODO: use team permissions
            if tool.team and request.user not in tool.team.members.all():
                messages.error(
                    request,
                    'You are not permitted to create tools for the team "{}".'
                        .format(tool.team.name))
                return redirect(reverse('tools:overview'))
            with transaction.atomic():
                tool.creator = request.user
                tool.save()
            tool.filename = '{}_{}'.format(tool.id,
                                           request.FILES['file'].name)
            tools_dir = root().makedirs(settings.TOOLS_PATH, recreate=True)
            with tools_dir.open(tool.filename, 'wb+') as f:
                for chunk in request.FILES['file']:
                    f.write(chunk)
            messages.success(request, 'The tool was successfully uploaded')
            tool.save()
            return redirect(reverse('tools:overview'))

    messages.error(request, 'There was an error with your upload. You can only upload files up to 2 MiB')
    return redirect(reverse('tools:overview'))


@tools_enabled
@login_required
def edit_tool(request, tool_id):
    if request.method == 'POST':
        tool = get_object_or_404(Tool, id=tool_id)
        changed_name = False
        changed_description = False
        changed_public = False
        changed_file = False
        public = 'public' in request.POST.keys()
        if tool.name != request.POST['name']:
            tool.name = request.POST['name']
            changed_name = True
        if tool.description != request.POST['description']:
            tool.description = request.POST['description']
            changed_description = True
        if tool.public != public:
            tool.public = public
            changed_public = True
        file_form = FileUploadForm(request.POST, request.FILES)
        if file_form.is_valid() and 'file' in request.FILES.keys():
            changed_file = True
            tools_dir = root().opendir(settings.TOOLS_PATH)
            old_name = tool.filename
            tool.filename = request.FILES['file'].name
            tools_dir.remove(old_name)
            with tools_dir.open(tool.filename, 'wb+') as f:
                for chunk in request.FILES['file']:
                    f.write(chunk)
        tool.save()
        msg = 'changed'
        if changed_name:
            msg += ' name'
        if changed_description:
            msg += ' description'
        if changed_public:
            msg += ' public status'
        if changed_file:
            msg += ' file'
        if not (changed_public or changed_description or changed_file or changed_name):
            msg += ' nothing'
        msg += ' in the tool'
        messages.warning(request, msg)
        return redirect(reverse('tools:overview'))


@tools_enabled
@login_required
def delete_tool(request, tool_id):
    if request.method == 'POST':
        tool = get_object_or_404(Tool, id=tool_id)
        if tool.has_perm('delete_tool', request.user):
            tools_dir = root().opendir(settings.TOOLS_PATH)
            try:
                tools_dir.remove(tool.filename)
            except ResourceNotFound:
                pass
            tool.delete()
        else:
            messages.error(request, 'You do not have the permission to delete the tool!')
    return redirect(reverse('tools:overview'))


@tools_enabled
@login_required
def download_tool(request, tool_id):
    tool = get_object_or_404(Tool, id=tool_id)
    if tool.has_perm('download_tool', request.user):
        tools_dir = root().opendir(settings.TOOLS_PATH)
        if tool.filename and tools_dir.isfile(tool.filename):
            with tools_dir.open(tool.filename, 'rb') as fh:
                response = HttpResponse(fh.read(), content_type="application")
                response['Content-Disposition'] = 'attachment; filename=' + tool.filename
                return response
        else:
            messages.error(request, 'There was an error accessing the tool')
    else:
        messages.error(request, 'You do not have the permission to download the tool!')
    return redirect(reverse('tools:overview'))

src/imagetagger/tools/templates/overview.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block bodyblock %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1>Tools</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% if not tools %}
                <div class="alert alert-warning" role="alert">
                    There are no tools uploaded yet!
                </div>
            {% endif %}
            {% for tool in tools %}
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="btn-group pull-right">
                                    {% if tool.id in edit_tools %}
                                        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#editModal{{ tool.id }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></button>
                                    {% endif %}
                                    {% if tool.id in delete_tools %}
                                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal{{ tool.id }}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
                                    {% endif %}
                                </div>
                                <h4>{% if not tool.public %}<span class="glyphicon glyphicon-lock" aria-hidden="true"></span>{% endif %}{{ tool.name }}</h4>
                            </div>
                            <div class="panel-body">
                                {% if tool.team %}
                                    <p>
                                        <b>
                                            Team:
                                        </b>
                                        <a href="{% url 'users:team' tool.team.id %}">
                                            {{ tool.team.name }}
                                        </a>
                                    </p>
                                {% endif %}
                                {%  if tool.creator %}
                                    <p>
                                        <b>
                                            Creator:
                                        </b>
                                        <a href="{% url 'users:user' tool.creator.id %}">
                                            {{ tool.creator }}
                                        </a>
                                    </p>
                                {% endif %}
                                <p>{{ tool.description }}</p>
                                    <a class="btn btn-primary pull-right" href="{% url 'tools:download' tool.id %}">
                                        Download <span class="glyphicon glyphicon-download" aria-hidden="true"></span>
                                    </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <p class="panel-title">
                        Upload tool
                    </p>
                </div>
                <div class="panel-body">
                    <form method="POST" enctype="multipart/form-data" action="{% url 'tools:create' %}">
                        {% csrf_token %}
                        <label for="id_name"><h4>{{ form.name.label }}: </h4></label>
                        {% render_field form.name class+='form-control' %}
                        {% for error in form.name.errors %}
                        <div class="alert alert-warning">{{ error }}</div>
                        {% endfor %}
                        <br>
                        <label for="id_description"><h4>{{ form.description.label }}: </h4></label>
                        {% render_field form.description class+='form-control' %}
                        {% for error in form.description.errors %}
                        <div class="alert alert-warning">{{ error }}</div>
                        {% endfor %}
                        <br>
                        <label for="id_team"><h4>{{ form.team.label }}: </h4></label>
                        {% render_field form.team %}
                        {% for error in form.team.errors %}
                        <div class="alert alert-warning">{{ error }}</div>
                        {% endfor %}
                        <br>
                        <label for="id_public"><h4>{{ form.public.label }}: </h4></label>
                        {% render_field form.public %}
                        {% for error in form.public.errors %}
                        <div class="alert alert-warning">{{ error }}</div>
                        {% endfor %}
                        <br>
                        <label for="id_file"><h4>{{ form.file.label }}: </h4></label>
                        {% render_field form.file %}
                        {% for error in form.file.errors %}
                        <div class="alert alert-warning">{{ error }}</div>
                        {% endfor %}
                        <br>
                        <p>{{ tool_upload_notice | safe}}</p>
                        <input class="btn btn-primary pull-right" type="submit" value="Upload">

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% for tool in tools %}
    {% if tool.id in delete_tools %}
        <!-- Modal  -->
        <!-- stolen from https://getbootstrap.com/docs/3.3/javascript/#modals -->
        <div class="modal fade" id="deleteModal{{ tool.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Delete {{ tool.name }}</h4>
                    </div>
                    <div class="modal-body">
                        Do you really want to delete {{ tool.name }}?
                    </div>
                    <div class="modal-footer">
                        <form method="POST" action="{% url 'tools:delete' tool.id %}" >
                            {% csrf_token %}
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
    {% if tool.id in edit_tools %}
        <!-- Modal  -->
        <!-- stolen from https://getbootstrap.com/docs/3.3/javascript/#modals -->
        <div class="modal fade" id="editModal{{ tool.id }}" tabindex="-1" role="dialog" aria-labelledby="editModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Edit {{ tool.name }}</h4>
                    </div>
                    <div class="modal-body">
                        <form method="POST" action="{% url 'tools:edit' tool.id %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            <label for="id_name"><h4>Name: </h4></label>
                            <input type="text" name="name" maxlength="100" class="form-control" required id="id_name" value="{{ tool.name }}"/>
                            <br>
                            <label for="id_description"><h4>Description: </h4></label>
                            <textarea name="description" cols="40" rows="10" class="form-control" required id="id_description" value="{{ tool.description }}">{{ tool.description }}</textarea>
                            <br>
                            <label for="id_public"><h4>Public: </h4></label>
                            <input type="checkbox" name="public" id="id_public" {%  if tool.public %} checked {% endif %}/>
                            <br>
                            <label for="id_file"><h4>File: </h4></label>
                            {% render_field file_form.file %}
                    </div>
                    <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endfor %}
{% endblock %}